[package]
name = "snake"
version = "0.1.0"
authors = ["Andrew Peterson andrewp2@iastate.edu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"